name: Build Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wg-easy'
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: production

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        push: false
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: ghcr.io/wg-easy/wg-easy:pr
